site_name: JDash
site_url: http://doc.jdash.io
pages: 
- Home: index.md
- Client Development: 
    - Client Home: client/index.md
    - Getting Started: client/getting-started.md
    - Basic Concepts: client/basic-concepts.md
    - Providers: client/working-with-providers.md
    - Working with Dashboards: client/working-with-dashboards.md
    - Dashlet Development: client/dashlet-development.md
    - Client Events: client/client-events.md
    # - Advanced Topics: client/advanced-topics.md
- Backend Development:
    - Backend Home: backend/index.md
    - NodeJS Development: backend/nodejs-dev.md
    - Asp.Net MVC Development: backend/aspnet-mvc-dev.md
    - .Net Core Development: backend/net-core-dev.md
    - JDash Cloud: backend/jdash-cloud.md    
    # - MongoDB: backend/using-mongodb.md
    # - MySQL: backend/using-mysql.md
    # - MSSQL: backend/using-mssql.md
docs_dir: src
site_dir: docs
theme_dir: cinder